### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by cbfranca** [nicolastakashi/linq-to-type#6]
Error when i try to install on Windows.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chok    idar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.    0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cleid\\AppData\\Ro    aming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "linq-to-type"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! linq-to-type@1.0.5 postinstall: `typings install && tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the linq-to-type@1.0.5 postinstall script 'typings install && t    sc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the linq-to-type package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs linq-to-type
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls linq-to-type
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projetos\contaum\Presentation\ContaUm.Presentation.Backoffice\npm-    debug.log

**Comment by nicolastakashi** [comment]
hey there!

What is the node version that you have installed?

I cloned the repository again but I cant reproduce these error

**Comment by cbfranca** [comment]
node 7.0.0
npm 3.10.9

**Comment by nicolastakashi** [comment]
Do you have typings and typescript installed?

I can`t reproduce it.

**Comment by cbfranca** [comment]
tsc 2.0.3
typings 1.3.2

**Comment by nicolastakashi** [comment]
My dear, how are you?

I'm sorry but I could not reproduce the error you passed me, I deleted my local repository and cloned again and ran the npm install command.

I'm using the same versions of the node, typings and typescript.

You can try to clone the repository again and run the command?

**Comment by cbfranca** [comment]
I'm fine, and you ?

So, i did not tried to clone and install. I junt tried to install from npm package.

I'll try again
